# Serial parameters
port         = "/dev/ttyACM0"
baud_rate    = 115200

# Sampling & upload
sample_folder = "/home/pi/data/spool"
error_folder  = "/home/pi/data/errors"
upload_period_minutes = 15
heartbeat_period_minutes = 60

# Server
server_url   = "https://your-server.com"
ingest_path  = "/api/ingest"
error_path   = "/api/errors"
heartbeat_path = "/api/heartbeat"
device_token = "PUT-YOUR-LONG-RANDOM-SECRET-HERE"

# Local safety net
min_free_gb  = 0.5
zip_if_low_space = true
